require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - "*.gemspec"
    - Rakefile
    - "**/*.rake"
    - spec/**/*.rb
