sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6

before_install: gem install bundler -v 1.16.0

services:
  - redis-server

script:
  - bundle exec rspec
  - bundle exec rubocop

notifications:
  email: false
